# Generated by Django 4.0.2 on 2022-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photo/%Y/%M/%D')),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('insta_link', models.URLField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
