# Generated by Django 4.0.2 on 2022-03-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='teams',
            name='facebook_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='insta_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='twitter_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
