# Generated by Django 4.0.2 on 2022-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Salem', 'Salem'), ('Tiruppur', 'Tiruppur'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Vellore', 'Vellore'), ('Tirunelveli', 'Tirunelveli'), ('Erode', 'Erode'), ('Thoothukkudi', 'Thoothukkudi'), ('Dindigul', 'Dindigul'), ('Thanjavur', 'Thanjavur'), ('Hosur', 'Hosur'), ('Sivakasi', 'Sivakasi'), ('Karur', 'Karur'), ('Udhagamandalam', 'Udhagamandalam'), ('Ranipet', 'Ranipet'), ('Nagercoil', 'Nagercoil')], max_length=50)),
                ('state', models.CharField(choices=[('TN', 'TAMIL NADU'), ('other state', 'other state')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('congition', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('car_photo', models.ImageField(upload_to='photo/%Y/%M/%D')),
                ('car_photo1', models.ImageField(blank=True, upload_to='photo/%Y/%M/%D')),
                ('car_photo2', models.ImageField(blank=True, upload_to='photo/%Y/%M/%D')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photo/%Y/%M/%D')),
                ('car_photo4', models.ImageField(blank=True, upload_to='photo/%Y/%M/%D')),
                ('car_photo5', models.ImageField(blank=True, upload_to='photo/%Y/%M/%D')),
                ('features', models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=50)),
                ('body_style', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('MUV/SUV', 'MUV/SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Jeep', 'Jeep')], max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('trasmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
                ('interior', models.CharField(max_length=50)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('passenger', models.IntegerField()),
                ('vin_no', models.CharField(max_length=50)),
                ('millage', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric')], max_length=50)),
                ('no_of_owners', models.IntegerField()),
                ('is_featured', models.BooleanField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
